FROM alpine:latest
ARG TARGETARCH
RUN apk add --no-cache ca-certificates tzdata
COPY config-test.yml /etc/distribution/config.yml
COPY registry-$TARGETARCH /bin/registry
VOLUME ["/var/lib/registry"]
EXPOSE 80
ENTRYPOINT ["registry"]
ENV TZ=Asia/Shanghai \
    IMAGE_COPY_MODE=sync \
    IMAGE_PULL_TIMEOUT= \
    IMAGE_REPULL_MIN_INTERVAL= 
CMD ["serve", "/etc/distribution/config.yml"]